# Central Monitoring Configuration for all repositories

# Global settings
global:
  check_interval: 300  # 5 minutes
  timeout: 30  # seconds
  retries: 3
  alert_threshold: 0.8

# Alert channels
alerts:
  discord:
    enabled: true
    webhook_url: ${DISCORD_WEBHOOK_URL}
    channel_id: ${MONITORING_CHANNEL_ID}
  email:
    enabled: true
    recipients:
      - juansg777@gmail.com

# Repository specific checks
repository_checks:
  python:
    - type: pytest
      path: tests/
      timeout: 60
    - type: pip
      check: requirements.txt
    - type: lint
      tools: [pylint, black]
  
  node:
    - type: npm
      check: package.json
    - type: test
      script: test
    - type: lint
      tools: [eslint]
  
  go:
    - type: gotest
      path: ./...
    - type: golint
      path: ./...
    - type: gomod
      check: tidy

# Health checks
health_checks:
  endpoints:
    - name: API Health
      url: http://localhost:5000/health
      method: GET
      expected_status: 200
      timeout: 5
    
    - name: Admin Dashboard
      url: http://localhost:5001/admin/health
      method: GET
      expected_status: 200
      timeout: 5

  services:
    - name: Database
      type: postgresql
      port: 5432
      timeout: 5
    
    - name: Redis
      type: redis
      port: 6379
      timeout: 5

# Metrics collection
metrics:
  system:
    enabled: true
    collect:
      - cpu
      - memory
      - disk
      - network
  
  application:
    enabled: true
    collect:
      - response_time
      - error_rate
      - request_count
      - active_users

# Dashboard configuration
dashboard:
  title: "LYFF World Monitoring"
  refresh_interval: 30
  default_view: summary
  views:
    - name: summary
      components:
        - type: status_grid
          title: Repository Status
        - type: metrics_chart
          title: System Metrics
        - type: alert_list
          title: Recent Alerts
    
    - name: detailed
      components:
        - type: service_health
          title: Service Health Details
        - type: deployment_history
          title: Recent Deployments
        - type: error_log
          title: Error Log

# Integration points
integrations:
  github:
    enabled: true
    token: ${GITHUB_TOKEN}
    owner: lyffseba
  
  datadog:
    enabled: false
    api_key: ${DATADOG_API_KEY}
    app_key: ${DATADOG_APP_KEY}
  
  prometheus:
    enabled: true
    port: 9090
    path: /metrics

# Logging configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/monitoring.log
  max_size: 10MB
  backup_count: 5

