[build]
  command = "./build.sh"
  functions = "functions"
  publish = "web"

[build.environment]
  GO_IMPORT_PATH = "github.com/lyffseba/ana"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirect all traffic to index.html for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

