name: CI
# Reference: https://app.warp.dev/session/b660fd8a-f765-449c-a70c-f8c7b971e3c4?pwd=e9ccd7cb-d8be-494e-a2f2-35469f726896

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      if: hashFiles('go.mod') != ''
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Set up Python
      if: hashFiles('requirements.txt') != '' || hashFiles('setup.py') != '' || hashFiles('pyproject.toml') != ''
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Set up Node.js
      if: hashFiles('package.json') != ''
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Run tests
      run: |
        if [ -f go.mod ]; then
          go test ./...
        elif [ -f requirements.txt ]; then
          pip install -r requirements.txt
          pytest
        elif [ -f package.json ]; then
          npm install
          npm test
        fi
